runtime: python39

entrypoint: gunicorn -b :$PORT search_app:app

handlers:
- url: /api/.*
  script: auto

- url: /maps/.*
  script: auto

env_variables:
  FLASK_ENV: production
  # Add other environment variables here if needed