name: Deploy to Cloud Storage

on:
  push:
    branches:
      - main  # Deploy on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Google Cloud Credentials
        uses: google-github-actions/auth@v1  # Updated to the latest version
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Ensure this matches the secret you've set in GitHub

      - name: Deploy to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1  # Updated to the latest version
        with:
          path: ./frontend  # Adjust to the correct directory where your frontend files are located
          destination: precisionturn-frontend/  # Replace with your actual bucket name and optional subdirectory
          process_gcloudignore: false  # Set to false if you don't have a .gcloudignore file
